How to make a game so attractive
MacRoberto/AI-CHANGE.io pull request #14
Opened 2024-11-30 02:30 UTC by JJS74

Fixes https://github.com/MacRoberto/AI-CHANGE.io/issues/5

 

- [ ] Se realizo el header para esta pantalla
- [ ] Se realizo su contenido
- [ ] Se realizo footer
- [ ] La rama referente a esta asignación fue creada
- [ ] El commit se ha enviado
- [ ] Un pullrequest también fue realizado

![image](https://github.com/user-attachments/assets/f203a3d4-36c4-43fc-893f-c2ec89c55dd0)
![image](https://github.com/user-attachments/assets/a37c2e80-0970-41e6-b1ee-efae10dd8368)
![image](https://github.com/user-attachments/assets/f8c116ea-4471-4b4b-825c-d8916b7c8deb)
![image](https://github.com/user-attachments/assets/efb62c6e-7ced-4ab9-a54a-117039c5f455)

(Las imagenes fueron capturadas con un zoom del 80%, puede que no se vean como el resultado final)

2024-11-30 04:04 UTC, LuisAmir04 requested changes

2024-11-30 04:04 UTC, LuisAmir04 commented on img/Parrilla_erac.png
Que es esto?

2024-11-30 04:04 UTC, LuisAmir04 commented on img/Zarrin.svg
Ya estas usando un logo de Zarrin, agregar otro solo hara mas pesado la carpeta y la web

2024-11-30 04:04 UTC, LuisAmir04 commented on How_To_Attractive_Game.html
> +                    <a class="nav-link active fw-medium" aria-current="page" href="#" style="color: #7C4EE4;">Blog</a>
En este href que tiene puesto un # agrega el index.html para que puedas regresar desde ese boton hacia la pagina principal

2024-11-30 04:06 UTC, JJS74 commented on img/Parrilla_erac.png
AAAAAAA PERDON es un indio suelto seguramente se me habra movido automaticamente una discupa

2024-11-30 04:07 UTC, JJS74 commented on How_To_Attractive_Game.html
> +                    <a class="nav-link active fw-medium" aria-current="page" href="#" style="color: #7C4EE4;">Blog</a>
Entendido

2024-11-30 04:07 UTC, JJS74 commented on img/Zarrin.svg
Ya mismo lo arreglo, una disculpa

2024-11-30 04:35 UTC, JJS74 commented
fixes #7 

Se han removido y solucionado pequeños errores y otros elementos fuera de su lugar

2024-11-30 05:42 UTC, JJS74 commented
fixes #7

Interaccion entre paginas y responsivo arreglado, ya se puede acceder al contenido desde sus botones pertinentes

2024-11-30 05:56 UTC, LuisAmir04 approved these changes
Parece que ya esta todo correcto, gracias por responder

2024-11-30 08:00 UTC, Fernando7Josue approved these changes
Todo esta bien, aunque si se puede mejorar las posiciones de las lineas ya que se ve un poco desordenado

2024-12-01 19:31 UTC, Emiliano-dev25052 reviewed
![Imagen de WhatsApp 2024-12-01 a las 14 00 37_67e0bd78](https://github.com/user-attachments/assets/17fcc5bb-8571-452d-90a6-69636c99af7c)
Ese espacio entre el cierre de body y html es correcto? o no deberia estar alli, explicame para poder aprovar o pedir el cambio

2024-12-01 20:33 UTC, Emiliano-dev25052 commented
Tambien hace falta que se vincule la pagina index principal a tu parte

2024-12-02 00:36 UTC, MacRoberto commented
![image](https://github.com/user-attachments/assets/524dfbc1-aeb4-441c-99ba-4ba6b2cb904e)

En este desarrollo de page hace falta más espacio en el navbar (header o menú) según el desarrollo de figma.

![image](https://github.com/user-attachments/assets/76415d2b-ac79-4492-bb96-f0d7b53ed759)

2024-12-02 00:40 UTC, MacRoberto commented on pagina_noticia.html
> +                    <p>Google has been investing in AI for many years and bringing its benefits to individuals, businesses and communities. Whether it’s publishing state-of-the-art research, building
Sugiero que se ordene el texto en esta parte, para que se visualice de manera estético la estructura del código.

2024-12-02 00:48 UTC, MacRoberto commented on pagina_noticia.html
> +            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="To
Se debe alinear expanded a la línea correspondiente.

2024-12-02 00:57 UTC, MacRoberto commented on pagina_noticia.html
> +            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="To
Puedo ver en visual studio code que la alineación esta bien, es el menú files de github que hace estos ajustes porque excede la pantalla.
![image](https://github.com/user-attachments/assets/d91b54cb-2176-41ee-af75-93a2dcd42e78)

2024-12-02 01:12 UTC, merged